### ISSUE TITLE
Customize the display of the selected value

### ISSUE THREAD

**Issue by ened** [figengungor/country_pickers#10]
The current value display should, similar to the `itemBuilder` property for the list items, be customizable,.

**Comment by muarifer** [comment]
Hello,

List items depends to you. 
For example, in examples folder, you can customize _buildDialogItem. You see that list ui and return widget changed.

**Comment by function1983** [comment]
From the sample code [https://github.com/figengungor/country_pickers/blob/7f9e1eba9c5f8bc7b141825c00a04b96aad409b2/example/lib/main.dart#L122](https://github.com/figengungor/country_pickers/blob/7f9e1eba9c5f8bc7b141825c00a04b96aad409b2/example/lib/main.dart#L122)
```
                      CountryPickerDropdown(
                        initialValue: 'US',
                        itemBuilder: _buildDropdownItem,
                        onValuePicked: (Country country) {
                          print("${country.name}");
                        },
                        itemFilter: (c) =>
                            ['US', 'GB', 'CN'].contains(c.isoCode),
                      ),
```
