### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by muarifer** [figengungor/country_pickers#14]
Hello,

Thanks for your efforts.
Elinize sağlık, güzel bir kütüphane olmuş :)

I think it should be some improvements.

- [ ] Country Priority (Boost) in List (I choose Turkey as 1, Russia 2, USA 3 etc..)
- [ ] Alternative country names (For example: Turkey is same as Türkiye, Netherland same as Holland)
- [x] 3. Country Exclude List (Maybe i exclude some of countries)

**Comment by muarifer** [comment]
Oops, 

I see "itemFilter" in source code :)
Remove the 3. item.

**Comment by ziyan-junaideen** [comment]
How about the ability to sort?
I am using country names and it looks wired. Kind of sort by field would be good I think?

- Andorra
- United Arab Emirates
- Afganistan

**Comment by muarifer** [comment]
@ziyan-junaideen it's good idea

**Comment by figengungor** [comment]
Thanks for the kind words @muarifer =)

I'll think about first checkbox but I'm not sure about second(alternative names).

**Comment by figengungor** [comment]
I'll think about sort by field, too @ziyan-junaideen

**Comment by figengungor** [comment]
Alrightie, I added priority list and sort by field features with version 1.2.0. Thanks for suggestions.
