### ISSUE TITLE
Customize the list

### ISSUE THREAD

**Issue by yossefEl** [figengungor/country_pickers#15]
Can you please make this customizable istead of countries only..

**Comment by shrutikateiosys** [comment]
can we define list of country instead of showing all country ?

**Comment by figengungor** [comment]
I'm not sure what you want @yossefEl . Can you give an example?

**Comment by figengungor** [comment]
You can use `itemFilter` property to limit country list @shrutikateiosys 
Here is an example: https://github.com/figengungor/country_pickers/blob/5e35a635edea90c79e78ed53e3871e62b2035df1/example/lib/main.dart#L127
