### ISSUE TITLE
initial value

### ISSUE THREAD

**Issue by DalalShimlani** [figengungor/country_pickers#18]
can you provide a way how to get the  initial value(should be string)from code phone

**Comment by chongzheng1995** [comment]
Hello @DalalShimlani, you can try use the code below. Please refer to the picture to see the function of getCountryByPhoneCode.

`CountryPickerUtils.getCountryByPhoneCode(String phonecode)`

![asa](https://user-images.githubusercontent.com/27880708/75532644-5bf63600-5a4f-11ea-98f2-9a6e14431840.PNG)

**Comment by figengungor** [comment]
Thanks for the answer @chongzheng1995
