### ISSUE TITLE
Unable to load assets errors for country_currency_pickers

### ISSUE THREAD

**Issue by giorgio79** [figengungor/country_pickers#27]
Hello,

I am raising this issue in this queue as issues are disabled for https://github.com/learnpainless/country_currency_pickers.

I just installed that pub package, but all the assets are reported as missing when testing a dropdown field:

```
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/country_currency_pickers/assets/ad.png
```

**Comment by giorgio79** [comment]
Ah I notice the authors are different :/

**Comment by erperejildo** [comment]
I get the same issue with this package. What's the solution @giorgio79?
