### ISSUE TITLE
ItemBuilder Overflow

### ISSUE THREAD

**Issue by elvisgn** [figengungor/country_pickers#31]
Hi,
First of all, thanks for the fantastic package.

I'm trying to integrate the package to my app using the following itemBuilder
```
  Widget _buildDropdownItem(Country country) {
    return Row(
      children: <Widget>[
        CountryPickerUtils.getDefaultFlagImage(country),
        SizedBox(width: 16),
        Text("${country.name}", overflow: TextOverflow.ellipsis),
      ],
    );
  }
```
Almost identical to the sample in the package but only that its using a `country.name` and clipped incase the name is too long for the screen.

The problem is that, even for a short country name, the widget is overflowing the screen as below
<img width="288" alt="Screen Shot 2020-05-05 at 11 25 45 AM" src="https://user-images.githubusercontent.com/8165850/81043746-ecc01680-8ec3-11ea-9672-9305b3cd502d.png">

I can force a container size on the Text, but not sure how it would behave on various screens.

I also tried setting the `isExpanded = true`, didn't work.

Kindly help. Thanks.

**Comment by KeeganLiew** [comment]
I had similar issue and fixed it with
` Widget _buildDropdownItem(Country country) {
    return Container(
      height: 60.0,
      width: MediaQuery.of(context).size.width * 0.85,
      child: Row(
        children: <Widget>[
          CountryPickerUtils.getDefaultFlagImage(country),
          SizedBox(
            width: 16.0,
          ),
          Expanded(
            child: Text(
              country.name,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
          ),
          Text(
            "(${country.isoCode})",
            textAlign: TextAlign.end,
          ),
        ],
      ),
    );
  }
}`

**Comment by figengungor** [comment]
Thank you for your workaround @KeeganLiew I also refactored and added some examples in example project.
