### ISSUE TITLE
Error after upgrading packages from 1.2.1 to 1.3.0

### ISSUE THREAD

**Issue by rajeshpatil95** [figengungor/country_pickers#34]
Someone already raised a query regarding it, Below is the link:
https://stackoverflow.com/questions/62029936/i-have-a-couple-of-problems-when-i-upgraded-packages-in-my-flutter-app

**Comment by figengungor** [comment]
Looks like your flutter sdk needs to be upgraded. In the old version, onTap property isn't defined in Dropdown.
