### ISSUE TITLE
Country Code Not available for "Lao People's Democratic Republic"

### ISSUE THREAD

**Issue by kedark-ix** [figengungor/country_pickers#40]

**Comment by kedark-ix** [comment]
![image](https://user-images.githubusercontent.com/60125620/90382562-8c349e00-e09c-11ea-8134-9b7c99e02df0.png)

**Comment by BoLindJensen** [comment]
I fixed this and made a pull request, waiting for @figengungor ;)

Also I made local language translations, for enabling native language translations pr language.

**Comment by figengungor** [comment]
Fixed with [PR 56](https://github.com/figengungor/country_pickers/pull/56)
