### ISSUE TITLE
Country code and disable images in flutter driver test 

### ISSUE THREAD

**Issue by pinball83** [figengungor/country_pickers#49]
After adding this library my driver test start failing and images from assets did not display

**Comment by Abdi-Adan** [comment]
Requesting assistance for the same.

**Comment by pinball83** [comment]
@Abdi-Adan  There are exist workaround, you need add check that your application run under dreiver test and setup custom AssetBundle instead of
`runApp(FlApp());`
 change for this
`runApp(DefaultAssetBundle(
        bundle: TestAssetBundle(),
        child: YourApp(),
      ));
`
and TestAssetBundle implementation:
`class TestAssetBundle extends CachingAssetBundle {
  @override
  Future<String> loadString(String key, {bool cache = true}) async {
    final ByteData data = await load(key);
    if (data == null) throw FlutterError('Unable to load asset');
    return utf8.decode(data.buffer.asUint8List());
  }

  @override
  Future<ByteData> load(String key) async => rootBundle.load(key);
}`

**Comment by Abdi-Adan** [comment]
Adding assets folder from this package to the root of my project without having to refernce in pubspec.yaml seems to have worked
