### ISSUE TITLE
Update deprecated ButtonTheme.bar constructor in MyAlertDialog

### ISSUE THREAD

**Issue by mujtabaimad** [figengungor/country_pickers#53]
The utils/my_alert_dialog.dart file is using the constructor ButtonTheme.bar and it is deprecated now. It should be updated to ButtonBarTheme.

**Comment by TheHemantKaushik** [comment]
`ButtonTheme.bar` is removed in Flutter version `1.26.0-17.3.pre`. Please update ASAP.

**Comment by JulianKowalczuk** [comment]
No update for 9 months, I guess author forgot about this project...
