### ISSUE TITLE
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/country_pickers-1.3.0/lib/utils/my_alert_dialog.dart:139:36: Error: Method not found: 'ButtonTheme.bar'.       children.add(new ButtonTheme.bar(

### ISSUE THREAD

**Issue by emailsubjekt** [figengungor/country_pickers#69]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/country_pickers-1.3.0/lib/utils/my_alert_dialog.dart:139:36: Error: Method not found: 'ButtonTheme.bar'.
      children.add(new ButtonTheme.bar(

But I'm not even using country_pickers in my project. This makes no sense.

**Comment by figengungor** [comment]
Run flutter clean & flutter pub get commands. It looks like it's in the cache.
