### ISSUE TITLE
Add support to Flutter 3.22.0

### ISSUE THREAD

**Issue by BigAppsAndroid1** [figengungor/country_pickers#82]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/country_pickers-2.0.0/lib/utils/my_alert_dialog.dart:107:46: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.

**Comment by Matutez** [comment]
Hi With these changes it already compiles in flutter 3.22

in your pubspeck.yaml dependencies add this change.


`  country_pickers:
      git:
        url:https://github.com/Matutez/country_pickers.git
        ref:main
`

**Comment by figengungor** [comment]
Breaking changes have been fixed in version 3.0.0
